A task that will connect to the SQL database, fetch data from all tables and create a Cortex Dataset
coretex-ai/coretex-jobs pull request #170
Opened 2024-06-28 12:45 UTC by duskovesic

2024-07-01 15:56 UTC, VukManojlovic requested changes

2024-07-02 11:09 UTC, VukManojlovic requested changes

2024-07-02 11:09 UTC, VukManojlovic commented on tasks/sql-connector/main.py
> +        tableData = []
When defining empty lists and dictionaires typing should be added.
For example: `listVariable: list[str] = []`

2024-07-02 11:36 UTC, dule1322 requested changes

2024-07-02 11:36 UTC, dule1322 commented on tasks/sql-connector/main.py
> +        sampleNameZIP = f"{table}.zip"
We use camelCase style so `sampleNameCSV` -> `sampleNameCsv`, `sampleNameZIP` -> `sampleNameZip`

2024-07-02 11:36 UTC, dule1322 commented on tasks/sql-connector/main.py
> +
Remove this newline

2024-07-02 11:36 UTC, dule1322 commented on tasks/sql-connector/main.py
> +    if databaseType == "PostgreSQL":
This should be `elif`

2024-07-02 11:36 UTC, dule1322 commented on tasks/sql-connector/main.py
> +
Remove this newline

2024-07-02 11:36 UTC, dule1322 commented on tasks/sql-connector/task.yaml
> +name: SQL Connector
This should be called `transfer-data-from-sql-database`, or `upload-data-from-sql-database`. Also, `id` and `name` must match, we will be removing `name` completely soon, so keep them identical until we do.

2024-07-02 11:36 UTC, dule1322 commented on tasks/sql-connector/task.yaml
> +      - name: database_type
This name should be camelCase

2024-07-02 11:36 UTC, dule1322 commented on tasks/sql-connector/main.py
> +def fetchAllData(conn: Any, dataset: CustomDataset, queryGetTables: str, queryGetRows: str) -> None:
Why is `conn` of type `Any`? `Any` should almost never be used.

2024-07-02 11:36 UTC, dule1322 commented on tasks/sql-connector/main.py
> +    tables = [table[0] for table in tables]
Is `table[0]` guaranteed to not raise an index-out-of-bounds errror?

2024-07-05 07:59 UTC, dule1322 requested changes

2024-07-05 07:59 UTC, dule1322 commented on tasks/sql-connector/main.py
> +        raise RuntimeError("In the database, there are no tables")
I would change this to something like `There are no tables in the database`.

2024-07-05 07:59 UTC, dule1322 commented on tasks/sql-connector/main.py
> +        with open(sampleNameCsv, "w", newline="") as file:
There should be whitespace around `=` operator

2024-07-05 07:59 UTC, dule1322 commented on tasks/sql-connector/main.py
> +
Remove newline

2024-07-08 08:39 UTC, dule1322 approved these changes

2024-07-08 08:39 UTC, merged