CTX-5783: Mypy errors fixed
coretex-ai/coretex-jobs pull request #171
Opened 2024-07-01 12:50 UTC by VukManojlovic

2024-08-05 11:13 UTC, dule1322 requested changes
Can you check which libraries added to mypy config file have types and remove them from there?

2024-08-06 09:59 UTC, VukManojlovic commented on tasks/bio-bodysite-prediction/src/cache_json.py
> +    return hashCacheName(datasetName, suffix)[:20]
Not sure. Will change it back for now.

2024-08-06 09:59 UTC, VukManojlovic commented on tasks/bio-bodysite-prediction/src/load_data.py
> +        dataset.name[:42],
Not sure. Will change it back for now.v

2024-08-19 09:39 UTC, dule1322 requested changes

2024-08-19 09:39 UTC, dule1322 commented on tasks/qiime-import/mypy.ini
> +ignore_missing_imports = True
pandas has package called `pandas-stubs` which gets installed by running `mypy --install-types` so it should not be present in this file

2024-08-19 09:39 UTC, dule1322 commented on tasks/bio-read-quality/.mypy.ini
> +[mypy-matplotlib.*]
matplotlib has package called `matplotlib-stubs` which gets installed by running `mypy --install-types` so it should not be present in this file

2024-08-19 09:40 UTC, dule1322 commented on tasks/llm-text-processing/main.py
> +        responseContent = response["message"]["content"]  # type: ignore[index]
It is better as it keeps the code using expected types

2024-08-20 14:04 UTC, dule1322 approved these changes

2024-08-20 14:04 UTC, merged