CTX-5524: Created template for compiling onnx models to zkml format
coretex-ai/coretex-jobs pull request #177
Opened 2024-07-10 14:54 UTC by VukManojlovic

2024-07-11 13:42 UTC, bogdant36 commented on tasks/zkml-convert-model/main.py
> +import numpy as np
sort imports correctly

2024-07-11 13:42 UTC, bogdant36 commented on tasks/zkml-convert-model/main.py
> +    for item in source.rglob('*'):
use "" instead of ''

2024-07-11 13:42 UTC, bogdant36 commented on tasks/zkml-convert-model/main.py
> +            destItem.parent.mkdir(parents=True, exist_ok=True)
format properly whitespace around "="

2024-07-12 12:10 UTC, dule1322 requested changes

2024-07-12 12:10 UTC, dule1322 commented on tasks/zkml-convert-model/main.py
> +        elif item.is_file():
`elif` can be removed as the `if` is already doing `continue` if the criteria is met

2024-07-12 12:10 UTC, dule1322 commented on tasks/zkml-convert-model/task.yaml
> +  - name: inputVisibility
I'd rename this to `privateInput` or `publicInput`. Can you do this for other 2 visibility params as well?

2024-07-12 12:10 UTC, dule1322 commented on tasks/zkml-convert-model/main.py
> +    ctxModel.upload(modelDir)
Tag the model and you didn't submit it as output of this task as well.

2024-08-26 08:24 UTC, dule1322 approved these changes

2024-08-29 08:33 UTC, merged