Validation for image quality predictor
coretex-ai/coretex-jobs pull request #182
Opened 2024-07-18 13:18 UTC by duskovesic

2024-07-18 14:18 UTC, VukManojlovic requested changes

2024-07-18 14:18 UTC, VukManojlovic commented on tasks/image-quality-predictor/src/validation.py
> +    sigma = 0.5 / 3.5 # This value was chosen because the width of the Gaussian distribution function graph is the most suitable for the strictness of the metric
There should be two spaces between code and comment
`var = 0  # comment`

2024-07-18 14:31 UTC, VukManojlovic approved these changes

2024-07-24 09:15 UTC, dule1322 commented on tasks/image-quality-predictor/main.py
> +    if not taskRun.parameters["validation"]:
Extract bodies of `if`/`else` into two functions; `train` and `validate` and call them where appropriate

2024-07-31 13:12 UTC, merged