CTX-4914: Created image augmentation task template
coretex-ai/coretex-jobs pull request #55
Opened 2023-11-01 12:17 UTC by VukManojlovic

2023-11-27 12:20 UTC, dule1322 requested changes

2023-11-27 12:20 UTC, dule1322 commented on image-augmentation/task.yaml
> +    description: The image dataset from which images will be takenn for augmentation.
Fix typo

2023-11-27 12:20 UTC, dule1322 commented on image-augmentation/task.yaml
> +  - name: blurPrc
Rename to `blurPercentage`

2023-11-27 12:20 UTC, dule1322 commented on image-augmentation/task.yaml
> +  - name: useCache
Delete this parameter, let's handle this internally - if there is a dataset generated using same params submit that, otherwise generate a new one

2023-11-27 12:20 UTC, dule1322 commented on image-augmentation/task.yaml
> +  - name: useCache
Delete this parameter, let's handle this internally - if there is a dataset generated using same params submit that, otherwise generate a new one

2023-11-27 12:20 UTC, dule1322 commented on image-augmentation/src/utils.py
> +    imagePath.unlink(missing_ok = True)
There is no need to manually delete files stored inside `folder_manager.temp` directory. They get automatically deleted after an experiment has finished and before an experiment has started.

2023-11-27 12:20 UTC, dule1322 commented on image-augmentation/src/augmentation.py
> +
Remove newline

2023-11-27 12:20 UTC, dule1322 commented on image-augmentation/src/augmentation.py
> +        firstPipeline_ = firstPipeline_.to_deterministic()
Why is the `firstPipeline` name getting suffixed with an underscore?

2023-11-30 10:34 UTC, VukManojlovic commented on image-augmentation/task.yaml
> +
They were generated by a json to yaml conversion script. 
They have been removed manually.

2023-11-30 10:38 UTC, dule1322 approved these changes

2023-12-01 08:55 UTC, merged